# Generated by Django 3.2.5 on 2021-07-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='Class',
        ),
    ]
