# Generated by Django 3.2.5 on 2021-07-15 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_password_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accountbalance',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
